### ISSUE TITLE
It stops after only 3 Layers deep, why? 

### ISSUE THREAD

**Issue by AssBlaster69420** [emad-elsaid/dirtree#8]
I want to visualise my whole directory tree but the tool stops after 3 folders deep

**Comment by AssBlaster69420** [comment]
I really like this tool but this sucks

**Comment by emad-elsaid** [comment]
What's the command you're executing?

**Comment by AssBlaster69420** [comment]
$ dirtree -o output.html **/* *
#Visualize current directory recursively

It didn't mention any limit so I assumed it would recursively go as deep as the folder structure goes. But it always stops after the third layer. Maybe I'm just stupid idk.

**Comment by emad-elsaid** [comment]
Please read the readme file carefully gor the correct command and the shell
opt you jeed to turn on. This is a shell issue not dirtree
